services:
  bible-app:
    build: .
    container_name: bible-study-app
    restart: unless-stopped
    environment:
      API_KEY: ${API_KEY}
      DOMAIN: ${DOMAIN}
      SITE_TITLE: "Библейский кружок"
      SITE_SUBTITLE: "Комментарий для XXI века"
    volumes:
      - app-data:/app/data
    networks:
      - proxy

volumes:
  app-data:

networks:
  proxy:
    external: true
